-- MySQL Script generated by MySQL Workbench
-- Sat Oct 20 14:35:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pigwriter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pigwriter` ;

-- -----------------------------------------------------
-- Schema pigwriter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pigwriter` DEFAULT CHARACTER SET utf8 ;
USE `pigwriter` ;

-- -----------------------------------------------------
-- Table `pigwriter`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pigwriter`.`user` ;

CREATE TABLE IF NOT EXISTS `pigwriter`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pigwriter`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pigwriter`.`article` ;

CREATE TABLE IF NOT EXISTS `pigwriter`.`article` (
  `id` VARCHAR(32) NOT NULL,
  `title` VARCHAR(200) NULL,
  `content` TEXT NULL,
  `createDate` DATETIME NULL,
  `contentAbstract` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
